import os

ADOBE_SFTP_HOST = os.environ.get("ADOBE_SFTP_HOST")
ADOBE_SFTP_USER = os.environ.get("ADOBE_SFTP_USER")
ADOBE_SFTP_PASS = os.environ.get("ADOBE_SFTP_PASS")
ADOBE_PORTAL_EMAIL = os.environ.get("ADOBE_PORTAL_EMAIL")
ADOBE_PORTAL_PASS = os.environ.get("ADOBE_PORTAL_PASS")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
HUGGINGFACE_TOKEN = os.environ.get("HUGGINGFACE_TOKEN")
LEONARDO_API_KEY = os.environ.get("LEONARDO_API_KEY")
